name: code coverage
on: push
jobs:
  build:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: make child build dir
        run: mkdir ${{ runner.temp }}/child_build
      - name: make child build dir
        run: mkdir ${{ runner.temp }}/parent_build
      - name: build child
        run: cd ${{ runner.temp }}/child_build && cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ${{ github.workspace }}
      - name: build master
        run: git checkout master && cd ${{ runner.temp }}/parent_build && cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ${{ github.workspace }}
      - name: execute script
        run: python tools/parse_coverage.py ${{ runner.temp }}/child_build ${{ runner.temp }}/parent_build
      