name: code coverage
on: push
jobs:
  build:
    name: coverage
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: checkout child
        uses: actions/checkout@v2
      - name: setup build
        run: sudo apt update && sudo apt install ninja-build && sudo apt-get -y install cmake
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: make build dir
        run: mkdir ${{ runner.temp }}/child_build && mkdir ${{ runner.temp }}/parent_build
      - name: build child
        run: cd ${{ runner.temp }}/child_build && cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ${{ github.workspace }} && ninja -v && ctest -T Test && ctest -T Coverage
      - name: checkout master
        uses: actions/checkout@v2
        with:
          ref: master
      - name: build master
        run: cd ${{ runner.temp }}/parent_build && cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ${{ github.workspace }} && ninja -v && ctest -T Test && ctest -T Coverage
      - name: coverage status
        id: coverage
        run: |
          python tools/parse_coverage.py ${{ runner.temp }}/child_build ${{ runner.temp }}/parent_build
          COV_STATUS=$?
        continue-on-error: true
        # continue-on-error: true
      - name: check env.COV_STATUS
        run: |
          echo status is: ${{ env.COV_STATUS }}
      - name: check status
        # run: echo ${{steps.coverage.outputs.code}}
        if: env.COV_STATUS == '78'
        run: exit 1
      